excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://trolleway.github.io
title: trolleway
tagline: A log of everyday life
description: My awesome new site
paginate: 5
highlighter: rouge
